### ISSUE TITLE
参数 args.model_type 缺失

### ISSUE THREAD

**Issue by SP-FA** [laiyao1/chipformer#1]
在使用 `python odt.py --benchmark=adaptec1` 进行微调的时候发现在 odt.py 文件的 236 行使用了 args.model_type 这个参数，但是似乎并没有在其他位置找到相关的参数，因此运行之后会报错。请问该如何解决这个问题？

**Comment by laiyao1** [comment]
This error has been fixed. You can pull this repo and test it again.

Indeed, the args.model_type is not used in this repo. You can set it to any value.
