### ISSUE TITLE
Fixed Macro

### ISSUE THREAD

**Issue by Zl1-1** [laiyao1/chipformer#10]
Dear Authors,

In your paper，you mentioned that some fixed macros will be kept in their original positions, so how do you take into account the places reserved for fixed macros when placing other macros?

**Comment by laiyao1** [comment]
Dear Zl1-1, 

Thank you so much for your question. 

We fixed the IO macro pads for the adaptec1, adaptec2, and bigblue1. They are all located at the edges of the chip canvas, so when placing macros, we can simply exclude the positions around the perimeter.

**Comment by Zl1-1** [comment]
![734585c5387b3df94f766a6d605de85](https://github.com/laiyao1/chipformer/assets/154110627/a2f86ce0-89df-4ac5-9a3d-cce636944e54)
I have run the benchmark adaptec1 with DreamPlace and it shows the IO macros are not located at the edge of the canvas like the newblue1 benchmark? Have you changed the benchmark?
