### ISSUE TITLE
 graph_train.py  offset parameter

### ISSUE THREAD

**Issue by lovsfuc1ngsh1t** [laiyao1/chipformer#12]
I would like to know what the offset parameter in the file graph_train.py is prepared for, is it for macros that can be moved for more than 256 numbers? Or is it iterating over other benchmarks？If so, can I see an example of how to generate circuit tokens with more than 256 macros?
![Snipaste_2024-07-22_20-17-33](https://github.com/user-attachments/assets/36d111fe-355e-4e3c-bfe9-16f30d6df4ee)

**Comment by laiyao1** [comment]
Hello, thank you so much for your question.

The _offset_ parameter is not used in our code. 

For circuits with more than 256 macros:

1. When training, we use the first 256 macros.

2. During testing, when test_all_macro is set to true, all macros will be automatically placed. You can refer to get_returns in train_placement.py for specifics. The termination condition of Env (done=True) is when all macros are placed.
