### ISSUE TITLE
min_range in trainer_placement.py

### ISSUE THREAD

**Issue by ybj-catherine** [laiyao1/chipformer#17]
Dear laiyao,

I'm editing the project to generate floorplan for other benchmark circuits, but I'm not sure what min_range value (line 36 in trainer_placement.py) set for the certain circuit. Could u tell me how to determine the min_range value for the certain circuit? 

Thank you!

**Comment by laiyao1** [comment]
Hi,

The min_range is a rough estimate of the lower bound of the HPWL for the circuit, mainly used for reward normalization. You can first obtain an initial HPWL through online reinforcement learning or optimization algorithms (e.g., MaskPlace, Wiremask-BBO, etc.).
