### ISSUE TITLE
How to generate the optimal placement layout when setting macros and standard cells movable

### ISSUE THREAD

**Issue by ybj-catherine** [laiyao1/chipformer#5]
Dear Authors,

The paper says allowing macros still to be movable when performing optimization-based placement as Table 1 can reach the optimal solution. Is there any detailed descriptions or codes that can illustrate the layout generation?

Thanks a lot!

**Comment by laiyao1** [comment]
Thank you for your question.

Details can be found in mingpt/place_db.py. It reads the macros' sizes and connections and saves them in a database.
For the layout generation, it is got by our main file, run_dt_place.py. It can get each macro's positions (x,y) and that is the layout result.

**Comment by ybj-catherine** [comment]
> Thank you for your question.
> 
> Details can be found in mingpt/place_db.py. It reads the macros' sizes and connections and saves them in a database. For the layout generation, it is got by our main file, run_dt_place.py. It can get each macro's positions (x,y) and that is the layout result.


Thanks for your reply. I understand the layout you described is the output of phase 1 in Table 1, and my confusion is how is the output of phase 3 generated since the macos are already placed. What is the strategy of moving placed macros and standard cell?

Thank you! 
![image](https://github.com/laiyao1/chipformer/assets/90683795/6526ec14-662e-4e14-9381-368bc8c12a2a)

**Comment by laiyao1** [comment]
Thank you for your question.

The 3rd phase is implemented by the DREAMPlace. For its input, you can define whether each module is movable or fixed. The strategy is the same with DREAMPlace, and the parameters can be seen in your Appendix.

**Comment by ybj-catherine** [comment]
> > Thank you for your question.
> > Details can be found in mingpt/place_db.py. It reads the macros' sizes and connections and saves them in a database. For the layout generation, it is got by our main file, run_dt_place.py. It can get each macro's positions (x,y) and that is the layout result.
> 
> Thanks for your reply. I understand the layout you described is the output of phase 1 in Table 1, and my confusion is how is the output of phase 3 generated since the macos are already placed. What is the strategy of moving placed macros and standard cell?
> 
> Thank you! ![image](https://private-user-images.githubusercontent.com/90683795/328082488-6526ec14-662e-4e14-9381-368bc8c12a2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDE3ODUsIm5iZiI6MTcyMTg0MTQ4NSwicGF0aCI6Ii85MDY4Mzc5NS8zMjgwODI0ODgtNjUyNmVjMTQtNjYyZS00ZTE0LTkzODEtMzY4YmM4YzEyYTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE3MTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NTQ0YWIzOWJmNTJhZTc2Y2YzOWMzMTM3M2FiMGQwNzM5NmY5MzhiMWI4MWNhMDEwMWM0MjEzY2FlZDZiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RE5EbPvN3ga_Jv-OhcVgcApn49VAhwoVljzhfVHIHiM)

which detailed placer do you choose? I use DREAMPlace and find that the Detailed Placer need to be specified.

**Comment by smartbird66** [comment]
> Dear Authors,
> 
> The paper says allowing macros still to be movable when performing optimization-based placement as Table 1 can reach the optimal solution. Is there any detailed descriptions or codes that can illustrate the layout generation?
> 
> Thanks a lot!

hello bro.
I have the same problem.  Have you figured out how to use DRAMPlace to implement pahse3 in Table 1?

**Comment by laiyao1** [comment]
> > > 感谢您的提问。
> > > 详细信息可在 mingpt/place_db.py 中找到。它读取宏的大小和连接并将它们保存在数据库中。对于布局生成，它由我们的主文件 run_dt_place.py 获取。它可以获取每个宏的位置 (x,y)，这就是布局结果。
> > 
> > 
> > 谢谢你的回复。我理解你描述的布局是表 1 中第 1 阶段的输出，我感到困惑的是，既然 macos 已经放置好了，第 3 阶段的输出是如何生成的。移动放置的宏和标准单元的策略是什么？
> > 谢谢你！![图像](https://private-user-images.githubusercontent.com/90683795/328082488-6526ec14-662e-4e14-9381-368bc8c12a2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDE3ODUsIm5iZiI6MTcyMTg0MTQ4NSwicGF0aCI6Ii85MDY4Mzc5NS8zMjgwODI0ODgtNjUyNmVjMTQtNjYyZS00ZTE0LTkzODEtMzY4YmM4YzEyYTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE3MTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NTQ0YWIzOWJmNTJhZTc2Y2YzOWMzMTM3M2FiMGQwNzM5NmY5MzhiMWI4MWNhMDEwMWM0MjEzY2FlZDZiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RE5EbPvN3ga_Jv-OhcVgcApn49VAhwoVljzhfVHIHiM)
> 
> 您选择哪个详细布局器？我使用 DREAMPlace 并发现需要指定详细布局器。

详细布局器使用默认的就可以了，应该是内置的ABCDPlace，不用手动指定。
