### ISSUE TITLE
Where is GCN

### ISSUE THREAD

**Issue by FinAminToastCrunch** [laiyao1/chipformer#6]
Dear Authors,

In your paper, particularly the table 10 in the appendix, you state that you use a GCN to encode the circuit tokens within your model, however I do not see that anywhere in your code. Could you please clarify?

**Comment by laiyao1** [comment]
Dear S. Amin,

Thank you for your questions. The relevant GCN code has not been updated. We will update this part soon.

Authors

**Comment by anonyanalog** [comment]
Dear S. Amin,

Our repo has been updated with GCN.

Authors

**Comment by laiyao1** [comment]
Dear S. Amin,

Our code has been updated with GCN. Please check them. Thank you very much for your suggestions.

Authors

**Comment by FinAminToastCrunch** [comment]
Thanks so much!
