### ISSUE TITLE
trained_model.pkl 

### ISSUE THREAD

**Issue by lovsfuc1ngsh1t** [laiyao1/chipformer#9]
您好，我想问一下/save_models/trained_model.pkl 这个文件里面的模型参数，是通过那些数据集训练得到的？

**Comment by laiyao1** [comment]
Dear lovsfuc1ngsh1t,

Thank you so much for your question. This file is only an example model. We do not keep records of the datasets actually used for training. However, you can obtain models trained on any dataset through our open-source data and code.

Best regards,

Authors.
